CUDA_VISIBLE_DEVICES=0 python train/train_actor.py \
    --exp_suffix 15 \
    --category_types part  \
    --model_version model_actor_fir \
    --offline_data_dir ../data/PreGrasp_train_6 \
    --offline_data_dir2 ../data/PreGrasp_train_5 \
    --val_data_dir ../data/PreGrasp_val_3 \
    --train_buffer_max_num 15000  \
    --val_buffer_max_num 2000 \
    --feat_dim 160   \
    --batch_size 60  \
    --lr 0.001    \
    --lr_decay_every 500 \
    --lbd_kl 0.03     \
    --lbd_dir 5.0     \
    --z_dim 32   \
    --coordinate_system cambase \
    --use_boxed_pc
