CUDA_VISIBLE_DEVICES=0 python train/train_critic.py \
    --exp_suffix 15 \
    --category_types part  \
    --model_version model_critic_fir \
    --offline_data_dir ../data/PreGrasp_train_6 \
    --offline_data_dir2 ../data/PreGrasp_train_5 \
    --val_data_dir ../data/PreGrasp_val_3 \
    --train_buffer_max_num 15000  \
    --val_buffer_max_num 2000 \
    --feat_dim 160   \
    --batch_size 100  \
    --lr 0.0015 \
    --lr_decay_every 600 \
    --succ_proportion 0.4 \
    --fail_proportion 0.9 \
    --coordinate_system cambase \
    --loss_type L1Loss  \
    --use_boxed_pc  
